# Generated by Django 4.1.3 on 2022-11-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=2000)),
                ('track', models.TextField(choices=[('1', 'трек 1'), ('2', 'трек 2'), ('3', 'трек 3')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('projectID', models.IntegerField()),
                ('cp1', models.BooleanField(default=None)),
                ('cp2', models.BooleanField(default=None)),
                ('regist', models.BooleanField(default=None)),
                ('dostup', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='userC_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.IntegerField()),
                ('role', models.CharField(choices=[('dev', 'разработчик'), ('des', 'дизайнер'), ('manager', 'менеджер')], default='dev', max_length=20)),
                ('usersID', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='test_model',
        ),
    ]
