# Generated by Django 4.1.3 on 2022-11-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genz', '0002_projects_teams_userc_profile_delete_test_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='com1',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='projects',
            name='track',
            field=models.TextField(choices=[('1', 'трек 1'), ('2', 'трек 2'), ('3', 'трек 3')], max_length=50),
        ),
    ]
