# Generated by Django 4.1.3 on 2022-11-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genz', '0003_teams_com1_alter_projects_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='com2',
            field=models.TextField(default='', max_length=300),
        ),
    ]
