# Generated by Django 4.1.3 on 2022-11-25 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genz', '0005_remove_userc_profile_usersid_userc_profile_usersdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userc_profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userc_profile',
            name='usersData',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
