# Generated by Django 4.1.3 on 2022-11-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genz', '0006_remove_userc_profile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='dostup',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='regist',
        ),
        migrations.AlterField(
            model_name='teams',
            name='com1',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='teams',
            name='com2',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
